/// <reference types="vite/client" />
import { expect, test } from "vitest";

import { PRODUCTS, SUBCATEGORIES } from "./catalogue.ts";
import { BOOK } from "./company.ts";
import { ROUTES, cardSlug } from "./seo.ts";

/**
 * The committed cards, read off the filesystem at transform time. Globbing
 * rather than node:fs keeps this runnable without @types/node, and lazy so
 * the PNGs are never actually loaded — only their names are used.
 */
const CARD_FILES = new Set(
  Object.keys(import.meta.glob("../../public/og/*.png")).map((file) =>
    file.slice(file.lastIndexOf("/") + 1)
  )
);

test("every route path is listed once", () => {
  const paths = ROUTES.map((route) => route.path);
  expect(new Set(paths).size).toBe(paths.length);
});

test("every class and product in the catalogue has a route", () => {
  const paths = new Set(ROUTES.map((route) => route.path));

  for (const cls of BOOK) {
    if (!SUBCATEGORIES[cls.slug]) continue;
    expect(paths).toContain(`/categories/${cls.slug}`);
  }
  for (const slug of Object.keys(PRODUCTS)) {
    expect(paths).toContain(`/products/${slug}`);
  }
});

/** How a string is counted once it is escaped into the HTML file. */
const markupLength = (text: string) =>
  text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;")
    .length;

test("titles stay inside what search results render, measured as markup", () => {
  for (const route of ROUTES) {
    // Measured escaped, not decoded: one "&" costs five characters in the
    // file, and that is what length checkers report. The homepage title read
    // 59 decoded and was flagged at 63.
    expect(markupLength(route.title), route.path).toBeLessThanOrEqual(60);
  }
});

test("descriptions fit the search budget and the tighter social one", () => {
  for (const route of ROUTES) {
    expect(route.description.length, route.path).toBeLessThanOrEqual(160);
    expect(route.description.length, route.path).toBeGreaterThan(50);

    // Link previews show roughly 125 characters and truncate the rest.
    expect(route.socialDescription.length, route.path).toBeLessThanOrEqual(125);
    expect(route.socialDescription.length, route.path).toBeGreaterThan(40);
  }
});

test("the social description does not trail off mid-sentence", () => {
  for (const route of ROUTES) {
    // An ellipsis means the sentence-preferring shortener had nothing short
    // enough to keep whole — worth a hand-written line for that route.
    expect(route.socialDescription, route.path).not.toMatch(/…$/);
  }
});

test("no two routes share a title or a description", () => {
  const titles = ROUTES.map((route) => route.title);
  const descriptions = ROUTES.map((route) => route.description);
  expect(new Set(titles).size).toBe(titles.length);
  expect(new Set(descriptions).size).toBe(descriptions.length);
});

/**
 * Cards are generated by `npm run cards` and committed, so adding a route
 * without re-running it ships a page whose og:image 404s — a blank preview,
 * invisible until someone shares the link. This is the check that catches it.
 */
test("every route has a committed link-preview card", () => {
  expect(CARD_FILES.size).toBeGreaterThan(0);
  for (const route of ROUTES) {
    const card = `${cardSlug(route.path)}.png`;
    expect(CARD_FILES, `missing ${card} — run \`npm run cards\``).toContain(card);
  }
});

test("no card is left behind by a route that was removed", () => {
  const wanted = new Set(ROUTES.map((route) => `${cardSlug(route.path)}.png`));
  expect([...CARD_FILES].filter((file) => !wanted.has(file))).toEqual([]);
});

test("card copy is filled in on every route", () => {
  for (const route of ROUTES) {
    for (const field of ["kicker", "headline", "sub", "line"] as const) {
      expect(route.card[field].trim().length, `${route.path}.${field}`).toBeGreaterThan(0);
    }
  }
});
